# Generated by Django 4.2.4 on 2023-08-25 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=10)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='social.person')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('likes', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_posts', to='social.person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='like_posts',
            field=models.ManyToManyField(blank=True, related_name='liking_person', to='social.post'),
        ),
    ]
